export const techToFileTypes: Record<string, string[]> = {
  react: ['.js', '.jsx', '.ts', '.tsx', '.html', '.css', '.json'],
  typescript: ['.ts', '.tsx', '.d.ts'],
  node: ['.js', '.json'],
  html: ['.html', '.css', '.js'],
  python: ['.py', '.html', '.css', '.json'],
  java: ['.java', '.xml', '.properties'],
  ruby: ['.rb', '.erb', '.html.erb', '.yaml', '.json'],
  php: ['.php', '.html', '.css', '.js', '.json'],
  csharp: ['.cs', '.cshtml', '.asp', '.json'],
  go: ['.go', '.html', '.css', '.json'],
  swift: ['.swift', '.xcodeproj', '.plist'],
  kotlin: ['.kt', '.kts', '.xml'],
  rust: ['.rs', '.toml', '.md'],
  javascript: ['.js', '.jsx', '.mjs', '.cjs', '.json', '.html', '.css'],
  css: ['.css', '.scss', '.sass', '.less'],
  shell: ['.sh', '.bash', '.zsh', '.bashrc', '.bash_profile'],
  json: ['.json'],
  xml: ['.xml'],
  sql: ['.sql'],
  lua: ['.lua'],
  perl: ['.pl', '.pm', '.t'],
  scala: ['.scala', '.sbt'],
  dart: ['.dart'],
  r: ['.r', '.Rmd', '.rds'],
  julia: ['.jl'],
  clojure: ['.clj', '.cljs', '.cljc'],
  haskell: ['.hs', '.lhs'],
  elixir: ['.ex', '.exs'],
  fsharp: ['.fs', '.fsx'],
  vhdl: ['.vhd', '.vhdl'],
  assembly: ['.asm', '.s'],
  matlab: ['.m', '.mat'],
  sass: ['.sass', '.scss'],
  objectivec: ['.m', '.h'],
  objectivecpp: ['.mm', '.h'],
  actionscript: ['.as', '.fla'],
};
